task 2

In [1]:

import numpy as np
import cv2
img = cv2.imread('download.jpeg',0)
height, width = img.shape
bin_img_arr = np.zeros((height, width), dtype = np.uint8)
threshold = 127
for y in range(height):
    for x in range(width):
        if img[y][x] >= threshold:
            bin_img_arr[y][x] = 255
    else:
        bin_img_arr[y][x] = 0
cv2.imshow("Binary Image: ", bin_img_arr)
cv2.waitKey(0)
cv2.destroyAllWindows()


task 4

In [2]:
import numpy as np
import cv2
img = cv2.imread('download.jpeg',0)
height, width = img.shape
bin_img_arr = np.zeros((height, width), dtype = np.uint8)
threshold = 127
for y in range(height):
    for x in range(width):
        if img[y][x] >= threshold:
            bin_img_arr[y][x] = 255
    else:
        bin_img_arr[y][x] = 0
cv2.imshow("Binary Image: ", bin_img_arr)
cv2.waitKey(0)
cv2.destroyAllWindows()


task 1

In [3]:
import cv2
image = cv2.imread('download.jpeg')
height, width, channels = image.shape
print(f"Dimensions: {height}x{width}, Number of channels: {channels}")
cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


Dimensions: 194x259, Number of channels: 3


In [4]:
import os
import cv2
image_path = 'download.jpeg'
image_size = os.path.getsize(image_path)
print(f"Image size: {image_size} bytes")
modification_time = os.path.getmtime(image_path)
print(f"Last modification date: {modification_time}")
image = cv2.imread(image_path)
height, width, channels = image.shape
print(f"Height: {height}, Width: {width}")
bit_depth = image.dtype
print(f"Bit Depth: {bit_depth}")
coding_method = 'JPEG' if image_path.endswith('.jpg') else 'Unknown'
print(f"Coding Method: {coding_method}")


Image size: 6251 bytes
Last modification date: 1727972952.554088
Height: 194, Width: 259
Bit Depth: uint8
Coding Method: Unknown


In [5]:
import numpy as np
double_image = np.array([[300.0, -10.0, 150.0], [0.0, 500.0, 255.0]])
uint8_image = double_image.astype(np.uint8)
print("Original double values:")
print(double_image)
print("\nConverted to uint8:")
print(uint8_image)


Original double values:
[[300. -10. 150.]
 [  0. 500. 255.]]

Converted to uint8:
[[ 44 246 150]
 [  0 244 255]]
